# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
   # branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get current prices
        run: |
          echo "---set credentials---"
          git config credential.helper 'cache --timeout=120'
          git config user.email "eltonkola@gmail.com"
          git config user.name "Deployment Bot"
          echo "---get data---"
          TODAYS_DATE=$(date +%Y-%m-%d)
          BRANCH_NAME="demo_update_$TODAYS_DATE"
          git checkout -b $BRANCH_NAME
          rm currentprice.json
          curl https://api.coindesk.com/v1/bpi/currentprice.json > currentprice.json
          git add .
          git commit -m "update currencty $TODAYS_DATE"
          echo '---git push it ----'
          git push -f --set-upstream origin $BRANCH_NAME
          echo Create pr!      
          BODY="{
              \"head\": \"${BRANCH_NAME}\",
              \"base\": \"main\",
              \"title\": \"bot pr: ${TODAYS_DATE}\",
              \"body\": \"this is an automaticlly created pr\"
          }"
          echo "To post $BODY"  
          curl -v -u "eltonkola:${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -X POST https://api.github.com/repos/eltonkola/actionzdemo/pulls -d '${BODY}'
        
          echo Done!  
